base_score: 0.5
booster: gbtree
callbacks: null
colsample_bylevel: 1
colsample_bynode: 1
colsample_bytree: 0
early_stopping_rounds: null
enable_categorical: false
eval_metric: null
features: '[''City'', ''PaymentTier'', ''Age'', ''EverBenched'', ''ExperienceInCurrentDomain'']'
gamma: 4.318327871504353
gpu_id: -1
grow_policy: depthwise
importance_type: null
interaction_constraints: ''
learning_rate: 0.300000012
max_bin: 256
max_cat_to_onehot: 4
max_delta_step: 0
max_depth: 9
max_leaves: 0
min_child_weight: 6
missing: .nan
model_class: XGBClassifier
monotone_constraints: ()
n_estimators: 180
n_jobs: 0
num_parallel_tree: 1
objective: binary:logistic
predictor: auto
random_state: 0
reg_alpha: 43
reg_lambda: 1
sampling_method: uniform
scale_pos_weight: 1
subsample: 1
tree_method: exact
use_label_encoder: false
validate_parameters: 1
verbosity: null
